spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      max-lifetime: 1800000
      idle-timeout: 600000
      connection-timeout: 30000
      minimum-idle: 2
      maximum-pool-size: 10
      connection-test-query: SELECT 1
      validation-timeout: 5000

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        use_sql_comments: true
        globally_quoted_identifiers: true
      hibernate.generate_statistics: true

  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: false
    placeholder-replacement: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:MAIL_USERNAME}
    password: ${MAIL_PASSWORD:MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          ssl:
            trust: smtp.gmail.com

jwt:
  secret: ${JWT_SECRET:TEST_SECRET}
  expiration: 900000
  refreshExpiration: 604800000

s3:
  enabled: true
  client:
    endpoint: http://minio:9000
    region: us‑east‑1
    access‑key: ${S3_CLIENT_ACCESS_KEY:S3_CLIENT_ACCESS_KEY}
    secret‑key: ${S3_CLIENT_SECRET_KEY:S3_CLIENT_SECRET_KEY}
    bucket: avatars
    public-url: https://jobsyapp.ru
    maxSize: 2097152
    allowed-ext:
      - png
      - jpg
      - jpeg

search:
  max-skills: 10

confirmation:
  expirationMinutes: 5
  codeLength: 4
  cleanup:
    interval: 600000
    passwordResetInterval: 600000

skill:
  popular-limit: 10

novita:
  api:
    url: ${NOVITA_API_URL:NOVITA_API_URL}
    key: ${NOVITA_API_KEY_FILE:NOVITA_API_KEY}
    model: ${NOVITA_API_MODEL:NOVITA_API_MODEL}
    default-system-prompt: ${NOVITA_API_DEFAULT_SYSTEM_PROMPT:NOVITA_API_DEFAULT_SYSTEM_PROMPT}

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
          - httptrace
          - loggers
          - threaddump
          - heapdump
          - env
          - beans
          - scheduledtasks
  endpoint:
    health:
      show-details: always

geonames:
  api:
    base-url: http://api.geonames.org
    username: ${GEONAMES_USERNAME:demo}

validation:
  api:
    rest-countries:
      base-url: https://restcountries.com/v3.1
    countries-now:
      base-url: https://countriesnow.space/api/v0.1

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    net.ttddyy.dsproxy.listener: TRACE
    net.ttddyy.dsproxy.proxy: TRACE

datasource-proxy:
  enabled: true
  p6spy:
    enable-logging: true
    multiline: true
  query:
    log-parameters: true
    multiline: true
    single-line: false