spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  flyway:
    enabled: false
  #     locations: classpath:db/migration
  #     baseline-on-migrate: true
  #     validate-on-migrate: false

  logging:
    level:
      org.flywaydb: TRACE

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:MAIL_USERNAME}
    password: ${MAIL_PASSWORD:MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          ssl:
            trust: smtp.gmail.com

jwt:
  secret: ${JWT_SECRET:TEST_SECRET}
  expiration: ${JWT_EXPIRATION:3600}