name: Server CD

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts  

      - name: List files
        run: ls -la

      - name: Create app.env file
        run: |
          echo "DB_SOURCE=${{ secrets.DB_SOURCE }}" >> app.env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> app.env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> app.env
          echo "SERVER_ADDRESS=${{ secrets.SERVER_ADDRESS }}" >> app.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> app.env
          echo "JWT_EXPIRATION=${{ secrets.JWT_EXPIRATION }}" >> app.env
          echo "MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}" >> app.env
          echo "MAIL_PASSWORD =${{ secrets.MAIL_PASSWORD }}" >> app.env
          echo "S3_CLIENT_ACCESS_KEY=${{ secrets.S3_CLIENT_ACCESS_KEY }}" >> app.env
          echo "S3_CLIENT_SECRET_KEY=${{ secrets.S3_CLIENT_SECRET_KEY }}" >> app.env

      - name: Copy files to the server
        run: |
          eval $(ssh-agent -s)
          scp ./docker-compose.yml ./Caddyfile ./app.env ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:${{ secrets.APP_PATH }}/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker image for backend
        run: |
          docker build -t jonshilin/jobsy:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push jonshilin/jobsy:latest

      - name: Deploy backend to server
        run: |
          eval $(ssh-agent -s)
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'ENDSSH'
          cd ${{ secrets.APP_PATH }} &&
          docker compose pull app &&
          docker compose up -d 
          docker system prune -f
          ENDSSH
