name: Server CI

on:
  push:
    branches:
      - master
      - develop
      - bugfix/*
      - release/*
      - feature/*
  pull_request:
    branches:
      - master
      - develop
      - bugfix/*
      - release/*
      - feature/*

permissions:
  contents: read
  packages: write
  pull-requests: write

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_EXPIRATION: ${{ secrets.JWT_EXPIRATION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start Prometheus container
        run: |
            docker pull prom/prometheus:latest
            docker run -d \
            --name prometheus-ci \
            -p 9090:9090 \
            -v ${{ github.workspace }}/prometheus.yml:/etc/prometheus/prometheus.yml:ro \
            prom/prometheus:latest

      - name: Wait for Prometheus to be ready
        run: |
            for i in {1..10}; do
              if curl -sf http://localhost:9090/-/ready; then
                echo "Prometheus is up!" && break
              fi
              echo "Waiting for Prometheus..." && sleep 5
            done

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Build project
        run: ./gradlew clean build --no-daemon

      - name: Run tests
        run: ./gradlew test --no-daemon

      - name: Wait for PostgreSQL to be healthy
        run: sleep 10
